//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommerce.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public long Id { get; set; }
        public long EmpresaId { get; set; }
        public long TipoComprobantePorDefectoId { get; set; }
        public long ListaPrecioPorDefectoId { get; set; }
        public long DepositoPorDefectoId { get; set; }
        public bool PuestoDeCajaSeparado { get; set; }
        public bool SeCobraCubiertos { get; set; }
        public decimal MontoPorCubierto { get; set; }
        public bool GrabarProductoEnTodosDepositos { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual TipoComprobante TipoComprobantePorDefecto { get; set; }
        public virtual ListaPrecio ListaPrecioPorDefecto { get; set; }
        public virtual Deposito DepositoPorDefecto { get; set; }
    }
}
