//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommerce.AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloDatosContainer : DbContext
    {
        public ModeloDatosContainer()
            : base("name=ModeloDatosContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<CondicionIva> CondicionIvas { get; set; }
        public virtual DbSet<Sala> Salas { get; set; }
        public virtual DbSet<Mesa> Mesas { get; set; }
        public virtual DbSet<Perfil> Perfiles { get; set; }
        public virtual DbSet<Formulario> Formularios { get; set; }
        public virtual DbSet<Comprobante> Comprobantes { get; set; }
        public virtual DbSet<DetalleComprobante> DetalleComprobantes { get; set; }
        public virtual DbSet<Articulo> Articulos { get; set; }
        public virtual DbSet<Caja> Cajas { get; set; }
        public virtual DbSet<TipoComprobante> TipoComprobantes { get; set; }
        public virtual DbSet<DetalleCaja> DetalleCajas { get; set; }
        public virtual DbSet<Movimiento> Movimientos { get; set; }
        public virtual DbSet<Configuracion> Configuraciones { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Rubro> Rubros { get; set; }
        public virtual DbSet<SubRubro> SubRubros { get; set; }
        public virtual DbSet<Ingrediente> Ingredientes { get; set; }
        public virtual DbSet<FormaPago> FormaPagos { get; set; }
        public virtual DbSet<Tarjeta> Tarjetas { get; set; }
        public virtual DbSet<PlanTarjeta> PlanTarjetas { get; set; }
        public virtual DbSet<Banco> Bancos { get; set; }
        public virtual DbSet<Precio> Precios { get; set; }
        public virtual DbSet<ListaPrecio> ListaPrecios { get; set; }
        public virtual DbSet<Deposito> Depositos { get; set; }
        public virtual DbSet<CuentaCorriente> CuentaCorrientes { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<BajaArticulo> BajasArticulos { get; set; }
        public virtual DbSet<Proveedor> Proveedores { get; set; }
        public virtual DbSet<CuentaCorrienteProveedor> CuentaCorrienteProveedores { get; set; }
    }
}
