//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCommerce.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salon : Comprobante
    {
        public EstadoSalon Estado { get; set; }
        public int Comensales { get; set; }
        public Nullable<long> EmpleadoId { get; set; }
        public long MesaId { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Mesa Mesa { get; set; }
    }
}
